extensions:

receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]